# Generated by Django 5.0.9 on 2026-04-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Influencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle_ig', models.CharField(blank=True, max_length=100)),
                ('handle_tiktok', models.CharField(blank=True, max_length=100)),
                ('handle_x', models.CharField(blank=True, max_length=100)),
                ('link_ig', models.URLField(blank=True)),
                ('link_tiktok', models.URLField(blank=True)),
                ('followers_ig', models.PositiveIntegerField(default=0)),
                ('followers_tiktok', models.PositiveIntegerField(default=0)),
                ('size_tier', models.CharField(blank=True, choices=[('NANO', 'Nano'), ('MICRO', 'Micro'), ('MACRO', 'Macro'), ('MEGA', 'Mega')], max_length=8)),
                ('er_ig', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('er_tiktok', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('engagement_level', models.CharField(blank=True, max_length=50)),
                ('niche', models.CharField(blank=True, max_length=100)),
                ('main_audience', models.CharField(blank=True, max_length=200)),
                ('age_range', models.CharField(blank=True, max_length=50)),
                ('gender', models.CharField(blank=True, max_length=50)),
                ('top_format', models.CharField(blank=True, max_length=100)),
                ('comm_style', models.CharField(blank=True, max_length=100)),
                ('ideal_campaign_type', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['handle_ig'],
            },
        ),
        migrations.CreateModel(
            name='CampaignInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MUST', 'Must'), ('ALTERNATIVE', 'Alternative'), ('NEGOTIATE_FEE', 'Negotiate fee'), ('DISCARDED', 'Discarded')], default='MUST', max_length=16)),
                ('fee_ars', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_per_engagement', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('includes_content', models.BooleanField(default=True)),
                ('includes_paid_boost', models.BooleanField(default=False)),
                ('previous_collabs', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_influencers', to='campaigns.campaign')),
                ('narrative_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='influencers', to='campaigns.narrativeline')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_influencers', to='campaigns.stage')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_assignments', to='influencers.influencer')),
            ],
            options={
                'ordering': ['campaign', '-status'],
                'unique_together': {('campaign', 'influencer')},
            },
        ),
    ]
