# Generated by Django 5.0.9 on 2026-04-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mother_concept', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=300)),
                ('objective', models.TextField(blank=True)),
                ('brief', models.TextField(blank=True, help_text='Narrative short description for the portal header.')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('FINISHED', 'Finished'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=16)),
                ('is_ongoing_operation', models.BooleanField(default=False, help_text="True for implicit 'Operación continua' campaigns used by brands without structured campaigns.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to='tenants.brand')),
            ],
            options={
                'ordering': ['-status', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='NarrativeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('tone', models.CharField(blank=True, max_length=100)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='narrative_lines', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['campaign', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('kind', models.CharField(choices=[('AWARENESS', 'Awareness'), ('EDUCATION', 'Educación'), ('VALIDATION', 'Validación'), ('CONVERSION', 'Conversión'), ('ONGOING', 'Ongoing'), ('OTHER', 'Other')], default='OTHER', max_length=16)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='campaigns.campaign')),
            ],
            options={
                'ordering': ['campaign', 'order'],
                'unique_together': {('campaign', 'order')},
            },
        ),
    ]
