# Generated by Django 5.0.9 on 2026-04-26 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('llm', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLMJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer', models.CharField(db_index=True, max_length=100)),
                ('handler_path', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Pendiente'), ('RUNNING', 'En curso'), ('SUCCESS', 'Éxito'), ('FAILED', 'Fallido')], db_index=True, default='PENDING', max_length=20)),
                ('input_metadata', models.JSONField(blank=True, default=dict)),
                ('output_metadata', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('total_input_tokens', models.PositiveIntegerField(default=0)),
                ('total_output_tokens', models.PositiveIntegerField(default=0)),
                ('total_cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('result_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_costs', 'Ver costos LLM')],
            },
        ),
        migrations.CreateModel(
            name='LLMCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='fireworks', max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('cost_usd', models.DecimalField(decimal_places=6, default=0, max_digits=10)),
                ('success', models.BooleanField(default=True)),
                ('error_type', models.CharField(blank=True, max_length=50)),
                ('error_message', models.TextField(blank=True)),
                ('request_payload', models.JSONField(blank=True, null=True)),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prompt_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='llm.promptversion')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='llm.llmjob')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='llmjob',
            index=models.Index(fields=['status', '-created_at'], name='llm_llmjob_status_cf7ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmjob',
            index=models.Index(fields=['consumer', '-created_at'], name='llm_llmjob_consume_7a07c8_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['job', '-created_at'], name='llm_llmcall_job_id_3c99b3_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['-created_at'], name='llm_llmcall_created_fd89f2_idx'),
        ),
        migrations.AddIndex(
            model_name='llmcall',
            index=models.Index(fields=['model', '-created_at'], name='llm_llmcall_model_8dc591_idx'),
        ),
    ]
