# Generated by Django 5.0.9 on 2026-04-18 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('INFLUENCER', 'Influencer'), ('GENERAL', 'General'), ('QUINCENAL', 'Quincenal'), ('MENSUAL', 'Mensual'), ('CIERRE_ETAPA', 'Cierre de etapa')], default='MENSUAL', max_length=16)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('title', models.CharField(blank=True, help_text='Auto-generated from kind + period if left blank.', max_length=300)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published')], default='DRAFT', max_length=12)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('conclusions_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='campaigns.stage')),
            ],
            options={
                'ordering': ['-period_start', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], max_length=16)),
                ('source_type', models.CharField(choices=[('ORGANIC', 'Orgánico'), ('INFLUENCER', 'Influencer'), ('PAID', 'Pauta')], max_length=16)),
                ('metric_name', models.CharField(help_text='e.g., reach, impressions, engagement_rate, followers_gained', max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('period_comparison', models.DecimalField(blank=True, decimal_places=4, help_text='Delta %% vs previous period (e.g., 12.4 for +12.4%%).', max_digits=8, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'network', 'source_type', 'metric_name'],
                'indexes': [models.Index(fields=['report', 'network', 'source_type'], name='reports_rep_report__088699_idx')],
            },
        ),
    ]
