# Generated by Django 5.0.9 on 2026-04-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Intro textual al principio del reporte (separada de conclusions_text).'),
        ),
    ]
