# Generated by Django 5.0.9 on 2026-04-20 17:25

import apps.reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_report_intro_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('POST', 'Post destacado'), ('CREATOR', 'Creator destacado')], max_length=16)),
                ('network', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], max_length=16)),
                ('source_type', models.CharField(choices=[('ORGANIC', 'Orgánico'), ('INFLUENCER', 'Influencer'), ('PAID', 'Pauta')], max_length=16)),
                ('rank', models.PositiveIntegerField(help_text='1-based ordering within (kind, network).')),
                ('handle', models.CharField(blank=True, max_length=120)),
                ('caption', models.TextField(blank=True)),
                ('thumbnail', models.ImageField(blank=True, upload_to='top_content/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('post_url', models.URLField(blank=True)),
                ('metrics', models.JSONField(blank=True, default=dict)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_content', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'kind', 'network', 'rank'],
                'indexes': [models.Index(fields=['report', 'kind'], name='reports_top_report__a36c96_idx')],
            },
        ),
    ]
