# Generated by Django 5.0.9 on 2026-04-20 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_topcontent'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandFollowerSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], max_length=16)),
                ('as_of', models.DateField()),
                ('followers_count', models.PositiveIntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follower_snapshots', to='tenants.brand')),
            ],
            options={
                'ordering': ['-as_of'],
                'unique_together': {('brand', 'network', 'as_of')},
            },
        ),
    ]
