# Generated by Django 5.0.9 on 2026-04-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_brandfollowersnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneLinkAttribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('influencer_handle', models.CharField(max_length=120)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('app_downloads', models.PositiveIntegerField(default=0)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onelink', to='reports.report')),
            ],
            options={
                'ordering': ['report', '-app_downloads'],
                'indexes': [models.Index(fields=['report'], name='reports_one_report__387c2d_idx')],
            },
        ),
    ]
