# Generated by Django 5.0.9 on 2026-04-21 00:57

import apps.reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_onelinkattribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='original_pdf',
            field=models.FileField(blank=True, help_text='PDF original del reporte (Google Slides export), descargable por el cliente.', null=True, upload_to='reports/pdf/%Y/%m/', validators=[apps.reports.validators.validate_pdf_size, apps.reports.validators.validate_pdf_mimetype]),
        ),
        migrations.CreateModel(
            name='ReportBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT_IMAGE', 'Texto + imagen'), ('KPI_GRID', 'Grilla de KPIs'), ('METRICS_TABLE', 'Tabla de métricas'), ('TOP_CONTENT', 'Best content'), ('ATTRIBUTION_TABLE', 'Tabla de atribución'), ('CHART', 'Gráfico')], max_length=32)),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, help_text='Solo usado por TEXT_IMAGE. En otros tipos se ignora.', null=True, upload_to='report_blocks/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order'],
                'indexes': [models.Index(fields=['report', 'order'], name='reports_rep_report__97023b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='reportblock',
            constraint=models.UniqueConstraint(fields=('report', 'order'), name='uniq_block_order_per_report'),
        ),
    ]
