# Generated by Django 5.0.9 on 2026-04-23 12:17

import apps.reports.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def _log_migration_applied(apps, schema_editor):
    import logging
    logger = logging.getLogger("reports.migrations")
    ReportBlock = apps.get_model("reports", "ReportBlock")
    logger.info(
        "typed_blocks_scaffold_applied",
        extra={"existing_blocks": ReportBlock.objects.count()},
    )


def _noop_reverse(apps, schema_editor):
    pass  # rollback no needs this log


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0008_topcontent_block_notnull'),
    ]

    operations = [
        # DEV-116: ReportBlock fue reemplazado por la versión polimórfica que
        # no declara `image`, `config`, `type`. Drop tanto state como DB aquí
        # — originalmente la intención era diferir el DB drop a 0011 (Task
        # 2.5), pero el RunSQL Postgres-specific para DROP NOT NULL rompía
        # el CI SQLite. Usar el RemoveField de Django (vendor-agnostic:
        # ALTER DROP COLUMN en Postgres, table rebuild en SQLite) resuelve
        # los dos problemas. Nada está en prod al momento del merge — la
        # data que vivía en esas columnas ya no se consume.
        migrations.RemoveField(
            model_name='reportblock',
            name='image',
        ),
        migrations.RemoveField(
            model_name='reportblock',
            name='config',
        ),
        migrations.RemoveField(
            model_name='reportblock',
            name='type',
        ),
        migrations.AddField(
            model_name='reportblock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reportblock',
            name='instructions',
            field=models.TextField(blank=True, help_text="Texto libre para guiar al AI (Metricool auto-fill) o al operador humano. Ej: 'mostrar solo posts con ads, ignorar los orgánicos de la campaña Q4 vieja'. No se renderiza en el viewer público."),
        ),
        migrations.AddField(
            model_name='reportblock',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='reportblock',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='reportblock',
            table='reports_reportblock',
        ),
        migrations.CreateModel(
            name='TextImageBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(blank=True)),
                ('columns', models.PositiveSmallIntegerField(choices=[(1, '1 columna'), (2, '2 columnas'), (3, '3 columnas')], default=1)),
                ('image_position', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha'), ('top', 'Arriba')], default='top', max_length=10)),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='report_blocks/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
            ],
            options={
                'verbose_name': 'Text + Image Block',
                'verbose_name_plural': 'Text + Image Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.RunPython(_log_migration_applied, _noop_reverse),
    ]
