# Generated by Django 5.0.9 on 2026-04-23 12:25

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_typed_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttributionTableBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('show_total', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Attribution Table Block',
                'verbose_name_plural': 'Attribution Table Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='ChartBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Metadata hint: red social que el chart representa.', max_length=16, null=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar')], default='bar', max_length=16)),
            ],
            options={
                'verbose_name': 'Chart Block',
                'verbose_name_plural': 'Chart Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='KpiGridBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'KPI Grid Block',
                'verbose_name_plural': 'KPI Grid Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='MetricsTableBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text="Metadata hint: red de social para la cual se arma la tabla. Null = cross-network (ej. 'Mes a mes'). Consumida por el fetcher AI de Metricool para saber qué data traer.", max_length=16, null=True)),
            ],
            options={
                'verbose_name': 'Metrics Table Block',
                'verbose_name_plural': 'Metrics Table Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='TopContentBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('POST', 'Post destacado'), ('CREATOR', 'Creator destacado')], max_length=16)),
                ('limit', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'Top Content Block',
                'verbose_name_plural': 'Top Content Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='ChartDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('order', models.PositiveIntegerField()),
                ('chart_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='reports.chartblock')),
            ],
            options={
                'ordering': ['chart_block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KpiTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('period_comparison', models.DecimalField(blank=True, decimal_places=4, help_text='Delta % vs periodo anterior. Opcional.', max_digits=8, null=True)),
                ('order', models.PositiveIntegerField()),
                ('kpi_grid_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='reports.kpigridblock')),
            ],
            options={
                'ordering': ['kpi_grid_block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MetricsTableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('source_type', models.CharField(blank=True, choices=[('ORGANIC', 'Orgánico'), ('INFLUENCER', 'Influencer'), ('PAID', 'Pauta')], max_length=16, null=True)),
                ('period_comparison', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('order', models.PositiveIntegerField()),
                ('metrics_table_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reports.metricstableblock')),
            ],
            options={
                'ordering': ['metrics_table_block', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='chartdatapoint',
            constraint=models.UniqueConstraint(fields=('chart_block', 'order'), name='uniq_point_order_per_chart'),
        ),
        migrations.AddConstraint(
            model_name='kpitile',
            constraint=models.UniqueConstraint(fields=('kpi_grid_block', 'order'), name='uniq_tile_order_per_kpi_grid'),
        ),
        migrations.AddConstraint(
            model_name='metricstablerow',
            constraint=models.UniqueConstraint(fields=('metrics_table_block', 'order'), name='uniq_row_order_per_metrics_table'),
        ),
    ]
