# Generated by Django 5.0.9 on 2026-04-23 12:34
#
# DEV-116 Task 2.5 — Destructive migration.
#
# Drops legacy columns/tables:
#   - ReportMetric table (entire model gone).
#   - ReportBlock.type, .config, .image DB columns (state-removed in 0009).
#   - TopContent.report FK (derivable via block.report).
#   - OneLinkAttribution.report FK (superseded by attribution_block).
#
# Migrates FKs:
#   - TopContent.block → TopContentBlock (was ReportBlock base).
#   - OneLinkAttribution adds attribution_block → AttributionTableBlock.
#
# Rollback is NOT safe: restore from backup or re-run seed_demo.
# At the time of this migration there is no production data.

import django.db.models.deletion
from django.db import migrations, models


def _log_destructive_migration(apps, schema_editor):
    import logging
    logger = logging.getLogger("reports.migrations")
    logger.warning(
        "typed_blocks_destructive_migration_applied",
        extra={
            "dropped": [
                "ReportMetric", "ReportBlock.type",
                "ReportBlock.config", "ReportBlock.image",
                "TopContent.report", "OneLinkAttribution.report",
            ],
            "note": "no prod data at time of migration",
        },
    )


def _warn_rollback_unsafe(apps, schema_editor):
    """Rollback is not safe — destructive migration cannot restore deleted data."""
    raise RuntimeError(
        "Migration 0011 is destructive and cannot be reversed automatically. "
        "Restore from backup or re-run seed_demo."
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_add_remaining_block_subtypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportmetric',
            name='report',
        ),
        migrations.AlterModelOptions(
            name='onelinkattribution',
            options={'ordering': ['attribution_block', '-app_downloads']},
        ),
        migrations.AlterModelOptions(
            name='topcontent',
            options={'ordering': ['block', 'kind', 'network', 'rank']},
        ),
        migrations.RemoveIndex(
            model_name='onelinkattribution',
            name='reports_one_report__387c2d_idx',
        ),
        migrations.RemoveIndex(
            model_name='topcontent',
            name='reports_top_report__a36c96_idx',
        ),
        migrations.RemoveField(
            model_name='onelinkattribution',
            name='report',
        ),
        migrations.RemoveField(
            model_name='topcontent',
            name='report',
        ),
        migrations.AddField(
            model_name='onelinkattribution',
            name='attribution_block',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='reports.attributiontableblock'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topcontent',
            name='block',
            field=models.ForeignKey(help_text='Bloque TOP_CONTENT que renderiza este ítem en el viewer.', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topcontentblock'),
        ),
        migrations.AddIndex(
            model_name='onelinkattribution',
            index=models.Index(fields=['attribution_block'], name='reports_one_attribu_504508_idx'),
        ),
        migrations.AddIndex(
            model_name='topcontent',
            index=models.Index(fields=['block', 'kind'], name='reports_top_block_i_acbe1e_idx'),
        ),
        migrations.DeleteModel(
            name='ReportMetric',
        ),
        # 0009 state-removed type/config/image from ReportBlock but kept the
        # DB columns (only NOT NULL dropped). Here we physically drop them.
        migrations.RunSQL(
            sql=(
                "ALTER TABLE reports_reportblock "
                "DROP COLUMN IF EXISTS type, "
                "DROP COLUMN IF EXISTS config, "
                "DROP COLUMN IF EXISTS image;"
            ),
            reverse_sql=migrations.RunSQL.noop,  # rollback no restaura data
        ),
        migrations.RunPython(_log_destructive_migration, _warn_rollback_unsafe),
    ]
