# Generated by Django 5.0.9 on 2026-04-23 20:19

import apps.reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_drop_legacy_and_migrate_fks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(help_text='Cualquier archivo descargable (PDF, XLSX, ZIP, ...).', upload_to='reports/attachments/%Y/%m/', validators=[apps.reports.validators.validate_pdf_size])),
                ('mime_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('kind', models.CharField(choices=[('PDF_REPORT', 'PDF del reporte'), ('DATA_EXPORT', 'Export de datos'), ('ANNEX', 'Anexo'), ('OTHER', 'Otro')], default='OTHER', help_text='Agrupación liviana para icono/orden en el viewer.', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order', 'id'],
                'indexes': [models.Index(fields=['report', 'order'], name='reports_rep_report__df60c1_idx')],
            },
        ),
    ]
