# Generated by Django 5.0.9 on 2026-04-23 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_migrate_original_pdf_to_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartblock',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line')], default='bar', max_length=16),
        ),
    ]
