# Generated by Django 5.0.9 on 2026-04-24 16:23

import apps.reports.validators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_chart_line_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopContentsBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, default='Top contenidos', max_length=200)),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Red social de los contenidos destacados.', max_length=16, null=True)),
                ('period_label', models.CharField(blank=True, help_text="Etiqueta de período mostrada en la cabecera, ej. 'febrero'.", max_length=60)),
                ('limit', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'Top Contenidos Block',
                'verbose_name_plural': 'Top Contenidos Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='TopCreatorsBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, default='Top creadores', max_length=200)),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Red social de los creadores destacados.', max_length=16, null=True)),
                ('period_label', models.CharField(blank=True, help_text="Etiqueta de período mostrada en la cabecera, ej. 'enero'.", max_length=60)),
                ('limit', models.PositiveSmallIntegerField(default=6, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
            ],
            options={
                'verbose_name': 'Top Creadores Block',
                'verbose_name_plural': 'Top Creadores Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.RemoveField(
            model_name='topcontentblock',
            name='reportblock_ptr',
        ),
        migrations.CreateModel(
            name='TopContentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='top_content/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('caption', models.TextField(blank=True)),
                ('post_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('ORGANIC', 'Orgánico'), ('INFLUENCER', 'Influencer'), ('PAID', 'Pauta')], default='ORGANIC', max_length=16)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('saves', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topcontentsblock')),
            ],
            options={
                'ordering': ['block', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopCreatorItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='top_creators/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('handle', models.CharField(help_text="Handle del creator (ej. '@antoroncatti'). Obligatorio.", max_length=120)),
                ('post_url', models.URLField(blank=True)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topcreatorsblock')),
            ],
            options={
                'ordering': ['block', 'order'],
            },
        ),
        migrations.DeleteModel(
            name='TopContent',
        ),
        migrations.DeleteModel(
            name='TopContentBlock',
        ),
        migrations.AddConstraint(
            model_name='topcontentitem',
            constraint=models.UniqueConstraint(fields=('block', 'order'), name='uniq_item_order_per_top_contents'),
        ),
        migrations.AddConstraint(
            model_name='topcreatoritem',
            constraint=models.UniqueConstraint(fields=('block', 'order'), name='uniq_item_order_per_top_creators'),
        ),
    ]
