# Generated by Django 5.0.9 on 2026-04-24 17:00

import apps.reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_split_top_content_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('image', models.ImageField(upload_to='image_blocks/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('overlay_position', models.CharField(choices=[('top', 'Arriba'), ('bottom', 'Abajo'), ('center', 'Centrado'), ('none', 'Sin overlay')], default='bottom', help_text="Dónde pintar el título+caption. 'none' deja la imagen sola.", max_length=10)),
            ],
            options={
                'verbose_name': 'Image Block',
                'verbose_name_plural': 'Image Blocks',
            },
            bases=('reports.reportblock',),
        ),
    ]
