# Generated by Django 5.0.9 on 2026-04-24 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_imageblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='kpitile',
            name='period_comparison_label',
            field=models.CharField(blank=True, help_text="Etiqueta del período de comparación (ej. 'vs feb'). Opcional.", max_length=30),
        ),
        migrations.AddField(
            model_name='kpitile',
            name='unit',
            field=models.CharField(blank=True, help_text="Unidad mostrada al lado del valor (ej. '%', 'm'). Opcional.", max_length=10),
        ),
    ]
