# Generated by Django 5.0.9 on 2026-04-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_kpitile_period_comparison_label_kpitile_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageblock',
            name='overlay_position',
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='caption',
            field=models.TextField(blank=True, help_text='Se renderea debajo de la imagen, separado por una línea. Si está vacío, esa sección se oculta.'),
        ),
        migrations.AlterField(
            model_name='imageblock',
            name='title',
            field=models.CharField(blank=True, help_text='Se renderea como pill title arriba del card.', max_length=200),
        ),
    ]
