# Generated by Django 5.0.9 on 2026-04-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0018_remove_imageblock_overlay_position_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartblock',
            name='description',
            field=models.TextField(blank=True, help_text='Frase descriptiva mostrada al lado del chart (hero layout).'),
        ),
    ]
