# Generated by Django 5.0.9 on 2026-04-27 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_chartblock_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableBlock',
            fields=[
                ('reportblock_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.reportblock')),
                ('title', models.CharField(blank=True, help_text="Pill title arriba de la tabla (ej. 'Instagram', 'Atribución OneLink').", max_length=200)),
                ('show_total', models.BooleanField(default=False, help_text="Si está activado, el frontend agrega una fila 'Total' al final sumando las columnas numéricas de las filas no-header.")),
            ],
            options={
                'verbose_name': 'Table Block',
                'verbose_name_plural': 'Table Blocks',
            },
            bases=('reports.reportblock',),
        ),
        migrations.CreateModel(
            name='TableRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_header', models.BooleanField(default=False, help_text='Si está activado, la fila se renderea con estilo de header (bold + uppercase + bg).')),
                ('cells', models.JSONField(default=list, help_text='Lista de strings, una por columna. El render formatea números/deltas automáticamente.')),
                ('table_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reports.tableblock')),
            ],
            options={
                'ordering': ['table_block', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='tablerow',
            constraint=models.UniqueConstraint(fields=('table_block', 'order'), name='uniq_row_order_per_table'),
        ),
    ]
