# Generated by Django 5.0.9 on 2026-04-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0020_table_block'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onelinkattribution',
            name='attribution_block',
        ),
        migrations.RemoveField(
            model_name='metricstableblock',
            name='reportblock_ptr',
        ),
        migrations.RemoveField(
            model_name='metricstablerow',
            name='metrics_table_block',
        ),
        migrations.DeleteModel(
            name='AttributionTableBlock',
        ),
        migrations.DeleteModel(
            name='OneLinkAttribution',
        ),
        migrations.DeleteModel(
            name='MetricsTableBlock',
        ),
        migrations.DeleteModel(
            name='MetricsTableRow',
        ),
    ]
