# Generated by Django 5.0.9 on 2026-04-27 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0021_drop_legacy_table_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, help_text='Pill title arriba de la sección. Vacío = sin pill.', max_length=200)),
                ('layout', models.CharField(choices=[('stack', 'Stack vertical'), ('columns_2', '2 columnas'), ('columns_3', '3 columnas')], default='stack', help_text='Cómo acomoda sus widgets. Stack = vertical full-width. Columns_2/3 = grid responsive (collapsa a 1 col en mobile).', max_length=16)),
                ('instructions', models.TextField(blank=True, help_text='Texto libre para guiar al AI o al operador. No se rendea.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, help_text='Subtítulo opcional dentro del widget (no es el pill — el pill vive en la Section). Renderizado depende del widget.', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Texto libre para guiar al AI o al operador. No se rendea.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.section')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['report', 'order'], name='reports_sec_report__e04ef4_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('report', 'order'), name='uniq_section_order_per_report'),
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['section', 'order'], name='reports_wid_section_a4b931_idx'),
        ),
        migrations.AddConstraint(
            model_name='widget',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_widget_order_per_section'),
        ),
    ]
