# Generated by Django 5.0.9 on 2026-04-27 16:12

import apps.reports.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('reports', '0021_drop_legacy_table_blocks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, help_text='Subtítulo opcional dentro del widget (no es el pill — el pill vive en la Section). Renderizado depende del widget.', max_length=200)),
                ('instructions', models.TextField(blank=True, help_text='Texto libre para guiar al AI o al operador. No se rendea.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('polymorphic_ctype', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_%(app_label)s.%(class)s_set+', to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['section', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True)),
                ('title', models.CharField(blank=True, help_text='Pill title arriba de la sección. Vacío = sin pill.', max_length=200)),
                ('layout', models.CharField(choices=[('stack', 'Stack vertical'), ('columns_2', '2 columnas'), ('columns_3', '3 columnas')], default='stack', help_text='Cómo acomoda sus widgets. Stack = vertical full-width. Columns_2/3 = grid responsive (collapsa a 1 col en mobile).', max_length=16)),
                ('instructions', models.TextField(blank=True, help_text='Texto libre para guiar al AI o al operador. No se rendea.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.report')),
            ],
            options={
                'ordering': ['report', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChartWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Metadata hint: red social que el chart representa.', max_length=16, null=True)),
                ('chart_type', models.CharField(choices=[('bar', 'Bar'), ('line', 'Line')], default='bar', max_length=16)),
            ],
            options={
                'verbose_name': 'Chart Widget',
                'verbose_name_plural': 'Chart Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='ImageWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('image', models.ImageField(upload_to='image_widgets/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Se renderea debajo de la imagen, separado por una línea. Si está vacío, esa sección se oculta.')),
            ],
            options={
                'verbose_name': 'Image Widget',
                'verbose_name_plural': 'Image Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='KpiGridWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
            ],
            options={
                'verbose_name': 'KPI Grid Widget',
                'verbose_name_plural': 'KPI Grid Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='TableWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('show_total', models.BooleanField(default=False, help_text="Si está activado, el frontend agrega una fila 'Total' al final sumando las columnas numéricas de las filas no-header.")),
            ],
            options={
                'verbose_name': 'Table Widget',
                'verbose_name_plural': 'Table Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='TextImageWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('body', models.TextField(blank=True)),
                ('columns', models.PositiveSmallIntegerField(choices=[(1, '1 columna'), (2, '2 columnas'), (3, '3 columnas')], default=1)),
                ('image_position', models.CharField(choices=[('left', 'Izquierda'), ('right', 'Derecha'), ('top', 'Arriba')], default='top', max_length=10)),
                ('image_alt', models.CharField(blank=True, max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='text_image_widgets/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
            ],
            options={
                'verbose_name': 'Text + Image Widget',
                'verbose_name_plural': 'Text + Image Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='TextWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('body', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Text Widget',
                'verbose_name_plural': 'Text Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='TopContentsWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Red social de los contenidos destacados.', max_length=16, null=True)),
                ('period_label', models.CharField(blank=True, help_text="Etiqueta de período mostrada en la cabecera, ej. 'febrero'.", max_length=60)),
            ],
            options={
                'verbose_name': 'Top Contenidos Widget',
                'verbose_name_plural': 'Top Contenidos Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.CreateModel(
            name='TopCreatorsWidget',
            fields=[
                ('widget_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='reports.widget')),
                ('network', models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter')], help_text='Red social de los creadores destacados.', max_length=16, null=True)),
                ('period_label', models.CharField(blank=True, help_text="Etiqueta de período mostrada en la cabecera, ej. 'enero'.", max_length=60)),
            ],
            options={
                'verbose_name': 'Top Creadores Widget',
                'verbose_name_plural': 'Top Creadores Widgets',
            },
            bases=('reports.widget',),
        ),
        migrations.AddField(
            model_name='widget',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='reports.section'),
        ),
        migrations.CreateModel(
            name='ChartDataPointWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=60)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('order', models.PositiveIntegerField()),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='reports.chartwidget')),
            ],
            options={
                'ordering': ['widget', 'order'],
            },
        ),
        migrations.CreateModel(
            name='KpiTileWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=4, max_digits=16)),
                ('unit', models.CharField(blank=True, help_text="Unidad mostrada al lado del valor (ej. '%', 'm'). Opcional.", max_length=10)),
                ('period_comparison', models.DecimalField(blank=True, decimal_places=4, help_text='Delta % vs periodo anterior. Opcional.', max_digits=8, null=True)),
                ('period_comparison_label', models.CharField(blank=True, help_text="Etiqueta del período de comparación (ej. 'vs feb'). Opcional.", max_length=30)),
                ('order', models.PositiveIntegerField()),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='reports.kpigridwidget')),
            ],
            options={
                'ordering': ['widget', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TableRowWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('is_header', models.BooleanField(default=False, help_text='Si está activado, la fila se renderea con estilo de header.')),
                ('cells', models.JSONField(default=list, help_text='Lista de strings, una por columna.')),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reports.tablewidget')),
            ],
            options={
                'ordering': ['widget', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopContentItemWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='top_content/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('caption', models.TextField(blank=True)),
                ('post_url', models.URLField(blank=True)),
                ('source_type', models.CharField(choices=[('ORGANIC', 'Orgánico'), ('INFLUENCER', 'Influencer'), ('PAID', 'Pauta')], default='ORGANIC', max_length=16)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('saves', models.PositiveIntegerField(blank=True, null=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topcontentswidget')),
            ],
            options={
                'ordering': ['widget', 'order'],
            },
        ),
        migrations.CreateModel(
            name='TopCreatorItemWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='top_creators/%Y/%m/', validators=[apps.reports.validators.validate_image_size, apps.reports.validators.validate_image_mimetype])),
                ('handle', models.CharField(help_text="Handle del creator (ej. '@antoroncatti'). Obligatorio.", max_length=120)),
                ('post_url', models.URLField(blank=True)),
                ('views', models.PositiveIntegerField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(blank=True, null=True)),
                ('comments', models.PositiveIntegerField(blank=True, null=True)),
                ('shares', models.PositiveIntegerField(blank=True, null=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='reports.topcreatorswidget')),
            ],
            options={
                'ordering': ['widget', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='widget',
            index=models.Index(fields=['section', 'order'], name='reports_wid_section_a4b931_idx'),
        ),
        migrations.AddConstraint(
            model_name='widget',
            constraint=models.UniqueConstraint(fields=('section', 'order'), name='uniq_widget_order_per_section'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['report', 'order'], name='reports_sec_report__e04ef4_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('report', 'order'), name='uniq_section_order_per_report'),
        ),
        migrations.AddConstraint(
            model_name='chartdatapointwidget',
            constraint=models.UniqueConstraint(fields=('widget', 'order'), name='uniq_point_order_per_chart_widget'),
        ),
        migrations.AddConstraint(
            model_name='kpitilewidget',
            constraint=models.UniqueConstraint(fields=('widget', 'order'), name='uniq_tile_order_per_kpi_grid_widget'),
        ),
        migrations.AddConstraint(
            model_name='tablerowwidget',
            constraint=models.UniqueConstraint(fields=('widget', 'order'), name='uniq_row_order_per_table_widget'),
        ),
        migrations.AddConstraint(
            model_name='topcontentitemwidget',
            constraint=models.UniqueConstraint(fields=('widget', 'order'), name='uniq_item_order_per_top_contents_widget'),
        ),
        migrations.AddConstraint(
            model_name='topcreatoritemwidget',
            constraint=models.UniqueConstraint(fields=('widget', 'order'), name='uniq_item_order_per_top_creators_widget'),
        ),
    ]
