# Generated by Django 5.0.9 on 2026-04-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_drop_blocks_and_rename_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartwidget',
            name='description',
            field=models.TextField(blank=True, help_text='Frase descriptiva grande mostrada al lado del chart (hero layout).'),
        ),
    ]
