# Generated by Django 5.0.9 on 2026-04-27 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_chartwidget_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandfollowersnapshot',
            name='network',
            field=models.CharField(choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter'), ('FACEBOOK', 'Facebook')], max_length=16),
        ),
        migrations.AlterField(
            model_name='chartwidget',
            name='network',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter'), ('FACEBOOK', 'Facebook')], help_text='Metadata hint: red social que el chart representa.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='topcontentswidget',
            name='network',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter'), ('FACEBOOK', 'Facebook')], help_text='Red social de los contenidos destacados.', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='topcreatorswidget',
            name='network',
            field=models.CharField(blank=True, choices=[('INSTAGRAM', 'Instagram'), ('TIKTOK', 'TikTok'), ('X', 'X/Twitter'), ('FACEBOOK', 'Facebook')], help_text='Red social de los creadores destacados.', max_length=16, null=True),
        ),
    ]
