# Generated by Django 5.0.9 on 2026-04-27 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_add_facebook_network'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportattachment',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Texto alternativo para accessibility (aria-label). Por defecto se usa el nombre del archivo.', max_length=255),
        ),
    ]
